name: Create Release and Upload Artifact

on:
  release:
    types:
      - created

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Extract release version
        id: extract_version
        run: echo "::set-output name=version::${{ github.ref#refs/tags/ }}"

      - name: Build with Gradle
        run: ./gradlew -Prelease=${{ github.event.release.tag_name }} packageDmg

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/distributions/my-application-${{ github.event.release.tag_name }}.dmg
          asset_name: my-application-${{ github.event.release.tag_name }}.dmg
          asset_content_type: application/octet-stream
